// Copyright (C) 2021 THL A29 Limited, a Tencent company. All rights reserved.
//
// Licensed under the BSD 3-Clause License (the "License"); you may not use this
// file except in compliance with the License. You may obtain a copy of the
// License at
//
// https://opensource.org/licenses/BSD-3-Clause
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

#ifndef FLARE_NET_COS_SIGNATURE_H_
#define FLARE_NET_COS_SIGNATURE_H_

#include <string>
#include <vector>

#include "flare/net/http/types.h"

namespace flare::cos {

// This method generates request signature using QCloud's algorithm.
//
// This method crashes if `uri` is not valid. As `uri` should be generated by
// your code purely, invalidity usually caused by programming error.
//
// Usually you don't need to provide `key_time` yourself. This method generate
// one automatically for you. The argument is provided mainly for testing
// purpose.
std::string GenerateCosAuthString(const std::string& secret_id,
                                  const std::string& secret_key,
                                  HttpMethod method, const std::string& uri,
                                  const std::vector<std::string>& hdrs,
                                  const std::string& key_time = "");

}  // namespace flare::cos

#endif  // FLARE_NET_COS_SIGNATURE_H_
